name: Deploy Tenshi

on:
  push:
    branches:
      - dev
      - stg
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy DEV
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            bash /home/vita-backend-dev/VitalinkBackendV2/deploy_tenshi.dev.sh

      - name: Deploy STG
        if: github.ref == 'refs/heads/stg'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_STG }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            bash /home/deploy/vitalinkBackendSTG/VitalinkBackendV2/deploy_tenshi.stg.sh

      - name: Deploy PROD
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            bash /home/deploy/vitalinkBackendPROD/VitalinkBackendV2/deploy_tenshi.prod.sh